
server:
  port: 8080

profile: local
# for database
spring:
  application:
    name:expense-tracker
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Expense-Tracker
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  profiles:
#    active: dev
# or else we can use CLI:-DSpring.profiles.active=dev or prod

info:
  app:
    name: Expense-tracker
    description: for tracking expenses
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,metrics
  info:
    env:
      enabled: true

#/+  profiles:
#    active: dev
#
#    url: jdbc:postgresql://localhost:5432/Expense-Tracker
#    username: postgres
#    password: 5432